[package]
name = "no_std_binary"
version = "0.1.0"

# abort_when_panic is not required, but recommend
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
#libc = { version = "*", default-features = false }
